server {
    listen 80;
    server_name ict-master.io;
    return 301 http://www.ict-master.io$request_uri;
}

server {
    listen 80;
    server_name www.ict-master.io;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://schooly-backend:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
